name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm ci

    - name: Deploy
      run: |
        git config --global user.name 'asharaghav'
        git config --global user.email 'z5363204@ad.unsw.edu.au'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy